/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */


export const styles: any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbmcyYmFzZS9iYXNlUHJvamVjdC9zcmMvYXBwL21vZHVsZS91c2VyL3VzZXIuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9uZzJiYXNlL2Jhc2VQcm9qZWN0L3NyYy9hcHAvbW9kdWxlL3VzZXIvdXNlci5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
