/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */


import * as i0 from './user.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './user.component';

const styles_UserComponent: any[] = [i0.styles];
export const RenderType_UserComponent: i1.RendererType2 = i1.ɵcrt({
	encapsulation: 0,
	styles: styles_UserComponent, data: {}
});

export function View_UserComponent_0(_l: any): i1.ɵViewDefinition {
	return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, (null as any), (null as any), 1, 'p', ([] as any[]),
		(null as any), (null as any), (null as any), (null as any), (null as any))), (_l()(),
		i1.ɵted(-1, (null as any), ['\n  user works!\n'])), (_l()(), i1.ɵted(-1, (null as any),
		['\n']))], (null as any), (null as any));
}

export function View_UserComponent_Host_0(_l: any): i1.ɵViewDefinition {
	return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, (null as any), (null as any), 1, 'app-user', ([] as any[]),
		(null as any), (null as any), (null as any), View_UserComponent_0, RenderType_UserComponent)),
		i1.ɵdid(1, 114688, (null as any), 0, i2.UserComponent, ([] as any[]), (null as any),
			(null as any))], (_ck, _v) => {
		_ck(_v, 1, 0);
	}, (null as any));
}

export const UserComponentNgFactory: i1.ComponentFactory<i2.UserComponent> = i1.ɵccf('app-user',
	i2.UserComponent, View_UserComponent_Host_0, {}, {}, ([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbmcyYmFzZS9iYXNlUHJvamVjdC9zcmMvYXBwL21vZHVsZS91c2VyL3VzZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L25nMmJhc2UvYmFzZVByb2plY3Qvc3JjL2FwcC9tb2R1bGUvdXNlci91c2VyLmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L25nMmJhc2UvYmFzZVByb2plY3Qvc3JjL2FwcC9tb2R1bGUvdXNlci91c2VyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovbmcyYmFzZS9iYXNlUHJvamVjdC9zcmMvYXBwL21vZHVsZS91c2VyL3VzZXIuY29tcG9uZW50LnRzLlVzZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgdXNlciB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtdXNlcj48L2FwcC11c2VyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFHO2FBQUEsMENBRUM7TUFBQTs7O29CQ0ZKO01BQUE7YUFBQTtVQUFBO0lBQUE7Ozs7In0=
