/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './user.module';
import * as i2 from '@angular/common';
import * as i3 from './user.service';
import * as i4 from '@angular/http';

export const UserModuleNgFactory: i0.NgModuleFactory<i1.UserModule> = i0.ɵcmf(i1.UserModule,
	([] as any[]), (_l: any) => {
		return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver,
			[[8, ([] as any[])], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(4608,
			i2.NgLocalization, i2.NgLocaleLocalization, [i0.LOCALE_ID]), i0.ɵmpd(4608, i3.UserService,
			i3.UserService, [i4.Http]), i0.ɵmpd(512, i2.CommonModule, i2.CommonModule, ([] as any[])),
			i0.ɵmpd(512, i1.UserModule, i1.UserModule, ([] as any[]))]);
	});
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovbmcyYmFzZS9iYXNlUHJvamVjdC9zcmMvYXBwL21vZHVsZS91c2VyL3VzZXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L25nMmJhc2UvYmFzZVByb2plY3Qvc3JjL2FwcC9tb2R1bGUvdXNlci91c2VyLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
